export const SET_NEW_LOCATION = "SET_NEW_LOCATION";

export const SET_CURRENT_CONDITIONS = 'SET_CURRENT_CONDITIONS';

export const SET_PAGE = 'SET_PAGE';

export const SET_FAVORITES_ARRAY = 'SET_FAVORITES_ARRAY';

export const SET_THEME = 'SET_THEME';

export const SET_TEMPERATURE_UNIT = 'SET_TEMPERATURE_UNIT';