export const SET_NEW_LOCATION = "SET_NEW_LOCATION";

export const SET_CURRENT_CONDITIONS = 'SET_CURRENT_CONDITIONS';

export const SET_PAGE = 'SET_PAGE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SET_FAVORITES_ARRAY = 'SET_FAVORITES_ARRAY';
